<?php
/**
 * Curated SCI icon metadata. SVG files remain separate, auditable sources.
 *
 * @package SCI\DesignBlocks
 */

return array(
	'hdd-rack' => array(
		'local_name'          => 'hdd-rack',
		'label'               => __( 'Server rack', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'hdd-rack',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'buildings' => array(
		'local_name'          => 'buildings',
		'label'               => __( 'Data center', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'buildings',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'cloud' => array(
		'local_name'          => 'cloud',
		'label'               => __( 'Cloud', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'cloud',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'database' => array(
		'local_name'          => 'database',
		'label'               => __( 'Database', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'database',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'hdd' => array(
		'local_name'          => 'hdd',
		'label'               => __( 'Storage drive', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'hdd',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'device-hdd' => array(
		'local_name'          => 'device-hdd',
		'label'               => __( 'NAS storage', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'device-hdd',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'cpu' => array(
		'local_name'          => 'cpu',
		'label'               => __( 'CPU', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'cpu',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'memory' => array(
		'local_name'          => 'memory',
		'label'               => __( 'Memory', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'memory',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'pc-display' => array(
		'local_name'          => 'pc-display',
		'label'               => __( 'Virtual machine', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'pc-display',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'boxes' => array(
		'local_name'          => 'boxes',
		'label'               => __( 'Container', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'boxes',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'diagram-3' => array(
		'local_name'          => 'diagram-3',
		'label'               => __( 'Network cluster', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'diagram-3',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'ethernet' => array(
		'local_name'          => 'ethernet',
		'label'               => __( 'Ethernet', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'ethernet',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'router' => array(
		'local_name'          => 'router',
		'label'               => __( 'Router', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'router',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'activity' => array(
		'local_name'          => 'activity',
		'label'               => __( 'System activity', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'activity',
		'conceptual_category' => 'Infrastructure & Cloud',
		'modified'            => false,
	),
	'shield-lock' => array(
		'local_name'          => 'shield-lock',
		'label'               => __( 'Firewall', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'shield-lock',
		'conceptual_category' => 'Security',
		'modified'            => false,
	),
	'lock' => array(
		'local_name'          => 'lock',
		'label'               => __( 'Lock', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'lock',
		'conceptual_category' => 'Security',
		'modified'            => false,
	),
	'unlock' => array(
		'local_name'          => 'unlock',
		'label'               => __( 'Unlock', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'unlock',
		'conceptual_category' => 'Security',
		'modified'            => false,
	),
	'fingerprint' => array(
		'local_name'          => 'fingerprint',
		'label'               => __( 'Fingerprint', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'fingerprint',
		'conceptual_category' => 'Security',
		'modified'            => false,
	),
	'bug' => array(
		'local_name'          => 'bug',
		'label'               => __( 'Malware / bug', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'bug',
		'conceptual_category' => 'Security',
		'modified'            => false,
	),
	'patch-check' => array(
		'local_name'          => 'patch-check',
		'label'               => __( 'Security certificate', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'patch-check',
		'conceptual_category' => 'Security',
		'modified'            => false,
	),
	'envelope-slash' => array(
		'local_name'          => 'envelope-slash',
		'label'               => __( 'Spam protection', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'envelope-slash',
		'conceptual_category' => 'Security',
		'modified'            => false,
	),
	'inbox' => array(
		'local_name'          => 'inbox',
		'label'               => __( 'Inbox', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'inbox',
		'conceptual_category' => 'Web & Communication',
		'modified'            => false,
	),
	'send' => array(
		'local_name'          => 'send',
		'label'               => __( 'Send message', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'send',
		'conceptual_category' => 'Web & Communication',
		'modified'            => false,
	),
	'envelope-check' => array(
		'local_name'          => 'envelope-check',
		'label'               => __( 'Verified email', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'envelope-check',
		'conceptual_category' => 'Web & Communication',
		'modified'            => false,
	),
	'envelope-exclamation' => array(
		'local_name'          => 'envelope-exclamation',
		'label'               => __( 'Email warning', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'envelope-exclamation',
		'conceptual_category' => 'Web & Communication',
		'modified'            => false,
	),
	'telephone' => array(
		'local_name'          => 'telephone',
		'label'               => __( 'Phone', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'telephone',
		'conceptual_category' => 'Web & Communication',
		'modified'            => false,
	),
	'headset' => array(
		'local_name'          => 'headset',
		'label'               => __( 'Headset support', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'headset',
		'conceptual_category' => 'Web & Communication',
		'modified'            => false,
	),
	'globe2' => array(
		'local_name'          => 'globe2',
		'label'               => __( 'Domain / DNS', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'globe2',
		'conceptual_category' => 'Web & Communication',
		'modified'            => false,
	),
	'window-desktop' => array(
		'local_name'          => 'window-desktop',
		'label'               => __( 'Web browser', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'window-desktop',
		'conceptual_category' => 'Web & Communication',
		'modified'            => false,
	),
	'code-slash' => array(
		'local_name'          => 'code-slash',
		'label'               => __( 'Code', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'code-slash',
		'conceptual_category' => 'Web & Communication',
		'modified'            => false,
	),
	'terminal' => array(
		'local_name'          => 'terminal',
		'label'               => __( 'Terminal', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'terminal',
		'conceptual_category' => 'Web & Communication',
		'modified'            => false,
	),
	'braces' => array(
		'local_name'          => 'braces',
		'label'               => __( 'API / code', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'braces',
		'conceptual_category' => 'Web & Communication',
		'modified'            => false,
	),
	'folder' => array(
		'local_name'          => 'folder',
		'label'               => __( 'Folder', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'folder',
		'conceptual_category' => 'Files & Backup',
		'modified'            => false,
	),
	'archive' => array(
		'local_name'          => 'archive',
		'label'               => __( 'Archive', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'archive',
		'conceptual_category' => 'Files & Backup',
		'modified'            => false,
	),
	'cloud-arrow-up' => array(
		'local_name'          => 'cloud-arrow-up',
		'label'               => __( 'Cloud backup', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'cloud-arrow-up',
		'conceptual_category' => 'Files & Backup',
		'modified'            => false,
	),
	'arrow-counterclockwise' => array(
		'local_name'          => 'arrow-counterclockwise',
		'label'               => __( 'Restore', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'arrow-counterclockwise',
		'conceptual_category' => 'Files & Backup',
		'modified'            => false,
	),
	'arrow-repeat' => array(
		'local_name'          => 'arrow-repeat',
		'label'               => __( 'Sync', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'arrow-repeat',
		'conceptual_category' => 'Files & Backup',
		'modified'            => false,
	),
	'copy' => array(
		'local_name'          => 'copy',
		'label'               => __( 'Copy', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'copy',
		'conceptual_category' => 'Files & Backup',
		'modified'            => false,
	),
	'clock-history' => array(
		'local_name'          => 'clock-history',
		'label'               => __( 'History', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'clock-history',
		'conceptual_category' => 'Files & Backup',
		'modified'            => false,
	),
	'building' => array(
		'local_name'          => 'building',
		'label'               => __( 'Company', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'building',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'briefcase' => array(
		'local_name'          => 'briefcase',
		'label'               => __( 'Business', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'briefcase',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'person-plus' => array(
		'local_name'          => 'person-plus',
		'label'               => __( 'Add person / partner', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'person-plus',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'truck' => array(
		'local_name'          => 'truck',
		'label'               => __( 'Supplier / delivery', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'truck',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'bullseye' => array(
		'local_name'          => 'bullseye',
		'label'               => __( 'Business target', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'bullseye',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'rocket-takeoff' => array(
		'local_name'          => 'rocket-takeoff',
		'label'               => __( 'Opportunity / launch', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'rocket-takeoff',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'piggy-bank' => array(
		'local_name'          => 'piggy-bank',
		'label'               => __( 'Cost savings', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'piggy-bank',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'speedometer2' => array(
		'local_name'          => 'speedometer2',
		'label'               => __( 'Productivity', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'speedometer2',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'person-workspace' => array(
		'local_name'          => 'person-workspace',
		'label'               => __( 'Consulting', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'person-workspace',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'file-earmark-text' => array(
		'local_name'          => 'file-earmark-text',
		'label'               => __( 'Contract', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'file-earmark-text',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'calendar-check' => array(
		'local_name'          => 'calendar-check',
		'label'               => __( 'Subscription', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'calendar-check',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'wallet2' => array(
		'local_name'          => 'wallet2',
		'label'               => __( 'Wallet', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'wallet2',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'credit-card' => array(
		'local_name'          => 'credit-card',
		'label'               => __( 'Credit card', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'credit-card',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'bank' => array(
		'local_name'          => 'bank',
		'label'               => __( 'Bank', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'bank',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'calculator' => array(
		'local_name'          => 'calculator',
		'label'               => __( 'Calculator', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'calculator',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'cash-coin' => array(
		'local_name'          => 'cash-coin',
		'label'               => __( 'ROI / return', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'cash-coin',
		'conceptual_category' => 'Business & SMEs',
		'modified'            => false,
	),
	'megaphone' => array(
		'local_name'          => 'megaphone',
		'label'               => __( 'Marketing campaign', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'megaphone',
		'conceptual_category' => 'Sales & Marketing',
		'modified'            => false,
	),
	'funnel' => array(
		'local_name'          => 'funnel',
		'label'               => __( 'Sales funnel', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'funnel',
		'conceptual_category' => 'Sales & Marketing',
		'modified'            => false,
	),
	'person-lines-fill' => array(
		'local_name'          => 'person-lines-fill',
		'label'               => __( 'Lead / audience', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'person-lines-fill',
		'conceptual_category' => 'Sales & Marketing',
		'modified'            => false,
	),
	'percent' => array(
		'local_name'          => 'percent',
		'label'               => __( 'Discount / percentage', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'percent',
		'conceptual_category' => 'Sales & Marketing',
		'modified'            => false,
	),
	'easel' => array(
		'local_name'          => 'easel',
		'label'               => __( 'Presentation', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'easel',
		'conceptual_category' => 'Sales & Marketing',
		'modified'            => false,
	),
	'mouse' => array(
		'local_name'          => 'mouse',
		'label'               => __( 'Click / interaction', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'mouse',
		'conceptual_category' => 'Sales & Marketing',
		'modified'            => false,
	),
	'person-vcard' => array(
		'local_name'          => 'person-vcard',
		'label'               => __( 'ID / contact', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'person-vcard',
		'conceptual_category' => 'People & Productivity',
		'modified'            => false,
	),
	'calendar-event' => array(
		'local_name'          => 'calendar-event',
		'label'               => __( 'Meeting / event', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'calendar-event',
		'conceptual_category' => 'People & Productivity',
		'modified'            => false,
	),
	'clock' => array(
		'local_name'          => 'clock',
		'label'               => __( 'Clock', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'clock',
		'conceptual_category' => 'People & Productivity',
		'modified'            => false,
	),
	'clipboard-check' => array(
		'local_name'          => 'clipboard-check',
		'label'               => __( 'Task / checklist', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'clipboard-check',
		'conceptual_category' => 'People & Productivity',
		'modified'            => false,
	),
	'diagram-2' => array(
		'local_name'          => 'diagram-2',
		'label'               => __( 'Workflow', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'diagram-2',
		'conceptual_category' => 'People & Productivity',
		'modified'            => false,
	),
	'gear-wide-connected' => array(
		'local_name'          => 'gear-wide-connected',
		'label'               => __( 'Automation', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'gear-wide-connected',
		'conceptual_category' => 'People & Productivity',
		'modified'            => false,
	),
	'puzzle' => array(
		'local_name'          => 'puzzle',
		'label'               => __( 'Integration', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'puzzle',
		'conceptual_category' => 'People & Productivity',
		'modified'            => false,
	),
	'mic' => array(
		'local_name'          => 'mic',
		'label'               => __( 'Microphone / speaker', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'mic',
		'conceptual_category' => 'Community & Events',
		'modified'            => false,
	),
	'broadcast' => array(
		'local_name'          => 'broadcast',
		'label'               => __( 'Live broadcast', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'broadcast',
		'conceptual_category' => 'Community & Events',
		'modified'            => false,
	),
	'ticket-perforated' => array(
		'local_name'          => 'ticket-perforated',
		'label'               => __( 'Event ticket / badge', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'ticket-perforated',
		'conceptual_category' => 'Community & Events',
		'modified'            => false,
	),
	'mortarboard' => array(
		'local_name'          => 'mortarboard',
		'label'               => __( 'Education / workshop', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'mortarboard',
		'conceptual_category' => 'Community & Events',
		'modified'            => false,
	),
	'tools' => array(
		'local_name'          => 'tools',
		'label'               => __( 'Workshop tools', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'tools',
		'conceptual_category' => 'Community & Events',
		'modified'            => false,
	),
	'crosshair' => array(
		'local_name'          => 'crosshair',
		'label'               => __( 'Focus / autofocus', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'crosshair',
		'conceptual_category' => 'Photography & Multimedia',
		'modified'            => false,
	),
	'lightning' => array(
		'local_name'          => 'lightning',
		'label'               => __( 'Camera flash', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'lightning',
		'conceptual_category' => 'Photography & Multimedia',
		'modified'            => false,
	),
	'brightness-high' => array(
		'local_name'          => 'brightness-high',
		'label'               => __( 'Exposure', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'brightness-high',
		'conceptual_category' => 'Photography & Multimedia',
		'modified'            => false,
	),
	'sliders' => array(
		'local_name'          => 'sliders',
		'label'               => __( 'Camera settings / ISO', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'sliders',
		'conceptual_category' => 'Photography & Multimedia',
		'modified'            => false,
	),
	'film' => array(
		'local_name'          => 'film',
		'label'               => __( 'Film roll', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'film',
		'conceptual_category' => 'Photography & Multimedia',
		'modified'            => false,
	),
	'filetype-raw' => array(
		'local_name'          => 'filetype-raw',
		'label'               => __( 'RAW photo', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'filetype-raw',
		'conceptual_category' => 'Photography & Multimedia',
		'modified'            => false,
	),
	'crop' => array(
		'local_name'          => 'crop',
		'label'               => __( 'Crop', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'crop',
		'conceptual_category' => 'Photography & Multimedia',
		'modified'            => false,
	),
	'camera-reels' => array(
		'local_name'          => 'camera-reels',
		'label'               => __( 'Video camera', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'camera-reels',
		'conceptual_category' => 'Photography & Multimedia',
		'modified'            => false,
	),
	'headphones' => array(
		'local_name'          => 'headphones',
		'label'               => __( 'Headphones', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'headphones',
		'conceptual_category' => 'Photography & Multimedia',
		'modified'            => false,
	),
	'play-fill' => array(
		'local_name'          => 'play-fill',
		'label'               => __( 'Play video', 'sci-design-blocks' ),
		'source'              => 'Bootstrap Icons',
		'source_version'      => 'v1.13.1',
		'source_name'         => 'play-fill',
		'conceptual_category' => 'Photography & Multimedia',
		'modified'            => false,
	),
);
